Repository opensearch-project/opensearch-jvector, pull requests merged in 2025-05, with the labels that each got.

#60 Make sure maven publish to all versions
  .github/workflows/maven-publish.yml
Labels: release, skip-changelog, backport 3.0

#69 Switch to lucene default reader
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  benchmark-jmh/build.gradle
  build.gradle
  gradle.properties
  qa/build.gradle
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorCodec.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorCompoundFormat.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorRandomAccessReader.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorReader.java
  src/test/java/org/opensearch/knn/index/codec/jvector/JVectorRandomAccessReaderTests.java
  src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java
  src/test/java/org/opensearch/knn/index/engine/InternalKNNEngineTests.java
  src/test/java/org/opensearch/knn/index/engine/JVectorConcurrentQueryTests.java
  src/test/resources/log4j2.properties
  src/test/resources/log4j2.xml
  src/testFixtures/java/org/apache/lucene/tests/mockfile/FixedFSProvider.java
Labels: backport 2.x, backport 2.19, backport 3.0

#77 use previous version of jVector
  benchmark-jmh/src/jmh/java/org/opensearch/knn/index/codec/jvector/datasets/MMapReader.java
  gradle.properties
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorFloatVectorValues.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorRandomAccessReader.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorReader.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorWriter.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNCounter.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStats.java
  src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
  src/test/java/org/opensearch/knn/index/engine/JVectorEngineIT.java
Labels: backport 3.0

#80 fix leak for file handles during query time
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorReader.java
  src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java
Labels: backport 3.0

#88 Switch to Lucene IndexInput writer and Introduce JVM memory analysis test
  CHANGELOG.md
  benchmark-jmh/src/jmh/java/org/opensearch/knn/index/codec/jvector/CachelessFormatBenchmarkRandomVectors.java
  benchmark-jmh/src/jmh/java/org/opensearch/knn/index/codec/jvector/FormatBenchmarkRandomVectors.java
  benchmark-jmh/src/jmh/java/org/opensearch/knn/index/codec/jvector/FormatBenchmarkWithKnownDatasets.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorFormat.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorIndexOutput.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorRandomAccessReader.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorRandomAccessWriter.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorReader.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorWriter.java
  src/main/java/org/opensearch/knn/plugin/JVectorKNNPlugin.java
  src/test/java/org/opensearch/knn/index/ThreadLeakFiltersForTests.java
  src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java
  src/test/java/org/opensearch/knn/index/codec/jvector/MemoryUsageAnalysisTests.java
  src/test/java/org/opensearch/knn/index/engine/JVectorConcurrentQueryTests.java
  src/test/java/org/opensearch/knn/index/engine/JVectorEngineIT.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: backport 3.0

#91 Use references for flat vectors
  CHANGELOG.md
  benchmark-jmh/src/jmh/java/org/opensearch/knn/index/codec/jvector/BenchmarkCommon.java
  build.gradle
  scripts/create_and_test_large_index.py
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorCodec.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorFloatVectorValues.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorFormat.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorRandomAccessReader.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorRandomAccessWriter.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorReader.java
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorWriter.java
  src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java
  src/test/java/org/opensearch/knn/index/codec/jvector/MemoryUsageAnalysisTests.java
  src/test/java/org/opensearch/knn/index/engine/JVectorEngineIT.java
Labels: backport 3.0

#96 Fix merge for deleted sorted index
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/knn/index/codec/jvector/JVectorWriter.java
  src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java
Labels: backport 3.0
